@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4NWVjODdlLWI2OGMtNDRlYi1hYzUyLTVhMWUzODRhNjY2NiIsInVzZXJOYW1lIjoiQWRtaW4xIiwicGFzc3dvcmQiOiJBZG1pbjEyMyEiLCJjcmVhdGVkQXQiOiIyMDI1LTAxLTEzVDE0OjA4OjExLjI0NloiLCJpYXQiOjE3MzY3NzcyOTMsImV4cCI6MTczOTM2OTI5M30.gUZsTsqQqW1h8sg87EQVwaiKozWZpmJcZVIAWA78Bxs
###
GET http://localhost:5000/api/v1/seeder/userSeeder
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "Admin1",
       "password" : "Admin123!"
}

###
get  http://localhost:5000/api/v1/userManagementAdmin/getUser
Content-Type: application/json
Authorization: Bearer {{token}}



###
get  http://localhost:5000/api/v1//userManagementAdmin/getUserById/9f1014f4-387c-4056-be39-12bcca5abbdd
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST  http://localhost:5000/api/v1//userManagementAdmin/createUser
Content-Type: application/json
Authorization: Bearer {{token}}


{     
       "userName"    : "Admin2",
       "password" : "Admin123!",
       "role" : "ADMIN"
}

###
PUT  http://localhost:5000/api/v1//userManagementAdmin/updateUserById/9f1014f4-387c-4056-be39-12bcca5abbdd
Content-Type: application/json
Authorization: Bearer {{token}}


{     
       "userName"    : "Admin3",
       "password" : "Admin123!",
       "role" : "DOKTER"

}

###
POST  http://localhost:5000/api/v1/userManagementAdmin/deleteUser/dc221ddc-fff8-4bdb-93af-94e610bd379a
Content-Type: application/json
Authorization: Bearer {{token}}


{     
       "userName"    : "Admin1",
       "password"    : "Admin123!"
}

